  Desenvolupament[m
  Incorporar-Readme[m
  chore/backend-ci[m
  docs/readme-backend[m
  feat/backend-initial-setup[m
  feature/TPS-clean[m
* [32mfeature/US-AI1-ValidacioAdminFinca[m
  feature/US13-ODintegration[m
  feature/US15-CalculEstimatEnergetic[m
  feature/accounts-update-endpoint[m
  feature/apps-bhs[m
  feature/apps-buildings[m
  feature/auth-final[m
  feature/configuracio-seguretat-entorns[m
  feature/control-acces[m
  feature/correccio-urls[m
  feature/db-testing[m
  feature/implementacio-millores[m
  feature/mireia[m
  feature/profile-management[m
  feature/prova-rules[m
  feature/provaReadme[m
  feature/rankings[m
  feature/staging-virtech[m
  feature/thirdPartyService[m
  feature/thirdPartyService-clean[m
  feature/thirdPartyService-fixed[m
  fix/TPS[m
  fix/role-semantics-owner-admin[m
  implementacio-uml[m
  issue/57-endpointHabitatge[m
  main[m
  prova-desenvolupament[m
  testing/thirdPartyService[m
