# Generated by Django 5.2.12 on 2026-04-29 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacio', models.FloatField()),
                ('posicio', models.IntegerField()),
                ('divisio', models.CharField(max_length=50)),
                ('edifici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='buildings.edifici')),
                ('lliga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='leagues.lliga')),
            ],
            options={
                'unique_together': {('edifici', 'lliga')},
            },
        ),
    ]
