# Generated by Django 5.2.12 on 2026-05-18 23:37

from django.db import migrations, models

def copiar_puntuacio_a_inicial(apps, schema_editor):
    Participacio = apps.get_model("participations", "Participacio")

    for p in Participacio.objects.all():
        p.puntuacio_inicial = p.puntuacio
        p.save(update_fields=["puntuacio_inicial"])

class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacio',
            name='puntuacio_inicial',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.RunPython(copiar_puntuacio_a_inicial),
    ]
