# Generated by Django 5.2.12 on 2026-05-18 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus', models.CharField(choices=[('nova_votacio', 'Nova votació'), ('votacio_tancada', 'Votació tancada'), ('votacio_cancellada', 'Votació cancel·lada')], max_length=50)),
                ('titol', models.CharField(max_length=200)),
                ('cos', models.TextField(blank=True)),
                ('llegida', models.BooleanField(default=False)),
                ('dataCreacio', models.DateTimeField(auto_now_add=True)),
                ('objecte_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('destinatari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dataCreacio'],
            },
        ),
    ]
