# Generated by Django 5.2.12 on 2026-04-29 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lliga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('EFICIENCIA', 'Eficiencia'), ('RESILIENCIA', 'Resiliencia'), ('PROGRES', 'Progres')], max_length=20)),
                ('divisio', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold')], max_length=10)),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporades', to='seasons.temporada')),
            ],
        ),
    ]
