# Generated by Django 5.2.12 on 2026-04-30 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0012_dadesenergetiquesopendata'),
        ('leagues', '0001_initial'),
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('EFICIENCIA', 'Eficiencia'), ('RESILIENCIA', 'Resiliencia'), ('PROGRES', 'Progres')], max_length=20)),
                ('puntuacio', models.FloatField()),
                ('posicio', models.IntegerField()),
                ('divisio', models.CharField(blank=True, max_length=50)),
                ('dataCalcul', models.DateTimeField(auto_now_add=True)),
                ('edifici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_historic', to='buildings.edifici')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_historic', to='seasons.temporada')),
            ],
            options={
                'ordering': ['temporada__dataInici', 'categoria', 'posicio'],
                'unique_together': {('edifici', 'temporada', 'categoria')},
            },
        ),
    ]
