# Generated by Django 5.2.12 on 2026-05-18 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0016_habitatge_estatvalidacio_habitatge_solicitant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Votacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=200)),
                ('descripcio', models.TextField(blank=True)),
                ('dataCreacio', models.DateTimeField(auto_now_add=True)),
                ('dataLimit', models.DateTimeField(blank=True, null=True)),
                ('estat', models.CharField(choices=[('oberta', 'Oberta'), ('tancada', 'Tancada'), ('cancel·lada', 'Cancel·lada')], default='oberta', max_length=20)),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votacions_creades', to=settings.AUTH_USER_MODEL)),
                ('edifici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votacions', to='buildings.edifici')),
            ],
            options={
                'ordering': ['-dataCreacio'],
            },
        ),
        migrations.CreateModel(
            name='OpcioVot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('votacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcions', to='community.votacio')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Vot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEmissio', models.DateTimeField(auto_now_add=True)),
                ('opcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vots', to='community.opciovot')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vots_emesos', to=settings.AUTH_USER_MODEL)),
                ('votacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vots', to='community.votacio')),
            ],
            options={
                'unique_together': {('votacio', 'usuari')},
            },
        ),
    ]
