# Generated by Django 5.2.12 on 2026-03-11 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edifici',
            fields=[
                ('id_edifici', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('any_construccio', models.IntegerField()),
                ('tipologia', models.CharField(choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial'), ('Mixt', 'Mixt')], max_length=20)),
                ('superficie_total', models.FloatField()),
                ('reglament', models.CharField(max_length=100)),
                ('orientacio_principal', models.CharField(max_length=50)),
                ('puntuacio_base', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Localitzacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrer', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('codi_postal', models.CharField(max_length=10)),
                ('barri', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('zona_climatica', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Habitatge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_cadastral', models.CharField(max_length=50)),
                ('planta', models.CharField(max_length=10)),
                ('porta', models.CharField(max_length=10)),
                ('superficie', models.FloatField()),
                ('any_reforma', models.IntegerField(blank=True, null=True)),
                ('edifici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitatges', to='buildings.edifici')),
            ],
        ),
        migrations.CreateModel(
            name='DadesEnergetiques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualificacio_global', models.CharField(max_length=2)),
                ('consum_energia_primaria', models.FloatField()),
                ('consum_energia_final', models.FloatField()),
                ('emissions_co2', models.FloatField()),
                ('cost_anual_energia', models.FloatField()),
                ('energia_calefaccio', models.FloatField(default=0)),
                ('energia_refrigeracio', models.FloatField(default=0)),
                ('energia_acs', models.FloatField(default=0)),
                ('energia_enllumenament', models.FloatField(default=0)),
                ('habitatge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dades_energetiques', to='buildings.habitatge')),
            ],
        ),
        migrations.AddField(
            model_name='edifici',
            name='localitzacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.localitzacio'),
        ),
    ]
