# Generated by Django 5.2.12 on 2026-03-18 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edifici',
            name='grupComparable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edificis', to='buildings.grupcomparable'),
        ),
        migrations.AlterField(
            model_name='edifici',
            name='idEdifici',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='edifici',
            name='puntuacioBase',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='localitzacio',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localitzacio',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localitzacio',
            name='zonaClimatica',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
