# Generated by Django 5.2.12 on 2026-03-18 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalegMillora',
            fields=[
                ('idMillora', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('descripcio', models.TextField(blank=True)),
                ('categoria', models.CharField(max_length=100)),
                ('impactePunts', models.FloatField(help_text='Punts que aporta al rànquing')),
                ('parametres', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='edifici',
            name='nombrePlantes',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='MilloraImplementada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataExecucio', models.DateField()),
                ('costReal', models.FloatField()),
                ('documentacioAdjunta', models.FileField(blank=True, null=True, upload_to='documents_millores/')),
                ('estatValidacio', models.CharField(choices=[('EnProces', 'En procés'), ('Validada', 'Validada'), ('Rebutjada', 'Rebutjada')], default='EnProces', max_length=20)),
                ('administradorFinca', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validacions', to=settings.AUTH_USER_MODEL)),
                ('edifici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implementacions', to='buildings.edifici')),
                ('millora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implementacions', to='buildings.catalegmillora')),
            ],
        ),
        migrations.CreateModel(
            name='SimulacioMillora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcio', models.CharField(max_length=255)),
                ('reduccioConsumPrevista', models.FloatField()),
                ('reduccioEmissionsPrevista', models.FloatField()),
                ('costEstimat', models.FloatField()),
                ('estalviAnual', models.FloatField()),
                ('dataSimulacio', models.DateField(auto_now_add=True)),
                ('edifici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulacions', to='buildings.edifici')),
                ('millora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulacions', to='buildings.catalegmillora')),
            ],
        ),
    ]
