# Generated by Django 5.2.12 on 2026-03-18 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_alter_edifici_grupcomparable_alter_edifici_idedifici_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingHealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('score', models.FloatField()),
                ('pesos', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bhs_history', to='buildings.edifici')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
