# Generated by Django 5.2.12 on 2026-03-19 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('buildings', '0002_alter_edifici_grupcomparable_alter_edifici_idedifici_and_more'),
        ('buildings', '0002_catalegmillora_edifici_nombreplantes_and_more'),
    ]

    operations = [
    ]
