# Generated by Django 5.2.12 on 2026-03-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_buildinghealthscore'),
        ('buildings', '0003_merge_20260319_1357'),
    ]

    operations = [
    ]
