# Generated by Django 5.2.12 on 2026-03-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_merge_20260319_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrersBarcelona',
            fields=[
                ('codi_via', models.AutoField(primary_key=True, serialize=False)),
                ('codi_carrer_ine', models.CharField(blank=True, max_length=50, null=True)),
                ('tipus_via', models.CharField(max_length=50)),
                ('nom_curt', models.CharField(max_length=100)),
                ('nom_oficial', models.CharField(max_length=150)),
                ('nre_min', models.IntegerField(blank=True, null=True)),
                ('nre_max', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
