# Generated by Django 5.2.12 on 2026-03-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_merge_20260319_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrersBarcelona',
            fields=[
                ('codi_via', models.AutoField(primary_key=True, serialize=False)),
                ('codi_carrer_ine', models.CharField(blank=True, max_length=20, null=True)),
                ('tipus_via', models.CharField(max_length=50)),
                ('nom_curt', models.CharField(max_length=255)),
                ('nom_oficial', models.CharField(max_length=255)),
                ('nre_min', models.IntegerField()),
                ('nre_max', models.IntegerField()),
            ],
        ),
    ]
