# Generated by Django 5.2.12 on 2026-03-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_carrersbarcelona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrersbarcelona',
            name='codi_carrer_ine',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carrersbarcelona',
            name='nom_curt',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carrersbarcelona',
            name='nom_oficial',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterModelTable(
            name='carrersbarcelona',
            table='carrers_barcelona',
        ),
    ]
