# Generated by Django 5.2.12 on 2026-04-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_carrersbarcelona'),
    ]

    operations = [
        migrations.AddField(
            model_name='edifici',
            name='actiu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='edifici',
            name='dataDesactivacio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edifici',
            name='motivDesactivacio',
            field=models.TextField(blank=True),
        ),
    ]
