# Generated by Django 5.2.12 on 2026-04-18 18:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0006_edifici_actiu_edifici_datadesactivacio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EdificiAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edifici_id_snapshot', models.IntegerField()),
                ('accio', models.CharField(choices=[('DESACTIVAR', 'Desactivar'), ('REACTIVAR', 'Reactivar'), ('CREAR', 'Crear'), ('ACTUALITZAR', 'Actualitzar'), ('ELIMINAR', 'Eliminar')], max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('camps_modificats', models.JSONField(blank=True, null=True)),
                ('motiu', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('edifici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='buildings.edifici')),
                ('usuari', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_edificis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Registre d'auditoria d'edifici",
                'verbose_name_plural': "Registres d'auditoria d'edificis",
                'ordering': ['-timestamp'],
            },
        ),
    ]
