# Generated by Django 5.2.12 on 2026-03-22 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0006_alter_carrersbarcelona_codi_carrer_ine_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carrersbarcelona',
            table=None,
        ),
    ]
