# Generated by Django 5.2.12 on 2026-04-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_edificiauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='edifici',
            name='classificacioEstimada',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], editable=False, help_text='Classificació energètica estimada (A–G). Null si no hi ha dades suficients.', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='edifici',
            name='classificacioFont',
            field=models.CharField(blank=True, choices=[('oficial', 'Oficial (certificat)'), ('estimada', 'Estimada (calculada)'), ('insuficient', 'Dades insuficients')], editable=False, help_text='Origen de la classificació: oficial, estimada o insuficient.', max_length=20, null=True),
        ),
    ]
