# Generated by Django 5.2.12 on 2026-04-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_edificiauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjudaVigent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=255)),
                ('organisme', models.CharField(max_length=100)),
                ('percentatgeMax', models.FloatField()),
                ('activa', models.BooleanField(default=True)),
                ('dataLimit', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Normativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=255)),
                ('urlReferencia', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='catalegmillora',
            name='parametres',
        ),
        migrations.AddField(
            model_name='catalegmillora',
            name='ambit',
            field=models.CharField(choices=[('Privat', 'Habitatge privat'), ('Comu', 'Element comú'), ('Edifici', 'Edifici complet')], default='Edifici', max_length=20),
        ),
        migrations.AddField(
            model_name='catalegmillora',
            name='bloquejadorsFrequents',
            field=models.JSONField(default=list, help_text='Ex: Edifici protegit, Façana catalogada'),
        ),
        migrations.AddField(
            model_name='catalegmillora',
            name='costMaxim',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='catalegmillora',
            name='costMinim',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='catalegmillora',
            name='estalviEnergeticEstimat',
            field=models.FloatField(default=0.0, help_text="% d'estalvi"),
        ),
        migrations.AddField(
            model_name='catalegmillora',
            name='nivellConfianca',
            field=models.CharField(choices=[('Baix', 'Baix'), ('Mig', 'Mig'), ('Alt', 'Alt')], default='Mig', max_length=10),
        ),
        migrations.AddField(
            model_name='catalegmillora',
            name='requereixAcordComunitat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catalegmillora',
            name='requereixCeePrePost',
            field=models.BooleanField(default=False, help_text='Certificat Energètic abans i després'),
        ),
        migrations.AddField(
            model_name='catalegmillora',
            name='requereixLlicenciaMunicipal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catalegmillora',
            name='requereixTecnicCompetent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catalegmillora',
            name='roiEstimatAnys',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalegmillora',
            name='tipusAcordEstimat',
            field=models.CharField(choices=[('No cal', 'No sol requerir acord'), ('MajoriaSimple', 'Majoria simple'), ('Majoria35', 'Majoria de 3/5'), ('Unanimitat', 'Unanimitat')], default='No cal', max_length=20),
        ),
        migrations.AddField(
            model_name='milloraimplementada',
            name='observacionsAdmin',
            field=models.TextField(blank=True, help_text='Motiu del rebutj o indicacions'),
        ),
        migrations.AddField(
            model_name='simulaciomillora',
            name='hipotesiBase',
            field=models.JSONField(blank=True, help_text='Còpia de les dades energètiques en el moment de la simulació', null=True),
        ),
        migrations.AlterField(
            model_name='catalegmillora',
            name='impactePunts',
            field=models.FloatField(default=0.0, help_text='Punts que aporta al rànquing'),
        ),
        migrations.AlterField(
            model_name='milloraimplementada',
            name='estatValidacio',
            field=models.CharField(choices=[('PendentDocumentacio', 'Pendent de documentació'), ('EnRevisió', 'En revisió'), ('Validada', 'Validada'), ('Rebutjada', 'Rebutjada')], default='PendentDocumentacio', max_length=20),
        ),
        migrations.AddField(
            model_name='catalegmillora',
            name='ajudesDisponibles',
            field=models.ManyToManyField(blank=True, to='buildings.ajudavigent'),
        ),
        migrations.AddField(
            model_name='catalegmillora',
            name='normativaAplicable',
            field=models.ManyToManyField(blank=True, to='buildings.normativa'),
        ),
    ]
