# Generated by Django 5.2.12 on 2026-03-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_alter_carrersbarcelona_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrersbarcelona',
            name='nre_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrersbarcelona',
            name='nre_min',
            field=models.IntegerField(default=0),
        ),
    ]
