# Generated by Django 5.2.12 on 2026-04-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_edifici_classificacioestimada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadesenergetiques',
            name='qualificacioGlobal',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=1, null=True),
        ),
    ]
