# Generated by Django 5.2.12 on 2026-03-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_alter_carrersbarcelona_nre_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrersbarcelona',
            name='nre_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carrersbarcelona',
            name='nre_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
