# Generated by Django 5.2.12 on 2026-04-26 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_ajudavigent_normativa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalegmillora',
            options={'ordering': ['categoria', 'nom'], 'verbose_name': 'Millora del catàleg', 'verbose_name_plural': 'Catàleg de millores'},
        ),
        migrations.AddField(
            model_name='catalegmillora',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='catalegmillora',
            name='costEstimatBase',
            field=models.FloatField(default=0, help_text='Cost orientatiu per unitat base. No és pressupost oficial.'),
        ),
        migrations.AddField(
            model_name='catalegmillora',
            name='mantenimentAnual',
            field=models.FloatField(default=0, help_text='Cost orientatiu anual de manteniment per unitat base.'),
        ),
        migrations.AddField(
            model_name='catalegmillora',
            name='parametresBase',
            field=models.JSONField(blank=True, default=dict, help_text='Paràmetres tècnics simplificats que utilitza el motor de simulació.'),
        ),
        migrations.AddField(
            model_name='catalegmillora',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador estable per seeds, frontend i motor de simulació.', max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='catalegmillora',
            name='unitatBase',
            field=models.CharField(choices=[('m2', 'm²'), ('unitat', 'Unitat'), ('kwp', 'kWp'), ('kwh', 'kWh'), ('habitatge', 'Habitatge'), ('edifici', 'Edifici')], default='edifici', max_length=30),
        ),
        migrations.AddField(
            model_name='catalegmillora',
            name='vidaUtil',
            field=models.IntegerField(default=0, help_text='Vida útil orientativa en anys.'),
        ),
        migrations.AddField(
            model_name='simulaciomillora',
            name='creadaPer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulacions_millores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simulaciomillora',
            name='resultat',
            field=models.JSONField(blank=True, default=dict, help_text='Resultat complet de la simulació: abans, després, deltes i hipòtesis.'),
        ),
        migrations.AddField(
            model_name='simulaciomillora',
            name='versioMotor',
            field=models.CharField(default='SIM-1.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='catalegmillora',
            name='bloquejadorsFrequents',
            field=models.JSONField(blank=True, default=list, help_text='Ex: Edifici protegit, façana catalogada.'),
        ),
        migrations.AlterField(
            model_name='catalegmillora',
            name='categoria',
            field=models.CharField(choices=[('envolupant', 'Envolupant tèrmica'), ('instal_lacio_termica', 'Instal·lació tèrmica'), ('renovables', 'Energies renovables'), ('electricitat', 'Electricitat'), ('mobilitat', 'Mobilitat'), ('control_i_monitoratge', 'Control i monitoratge')], default='envolupant', max_length=100),
        ),
        migrations.AlterField(
            model_name='simulaciomillora',
            name='costEstimat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='simulaciomillora',
            name='descripcio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='simulaciomillora',
            name='estalviAnual',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='simulaciomillora',
            name='hipotesiBase',
            field=models.JSONField(blank=True, help_text='Còpia de les dades energètiques en el moment de la simulació.', null=True),
        ),
        migrations.AlterField(
            model_name='simulaciomillora',
            name='millora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulacions_directes', to='buildings.catalegmillora'),
        ),
        migrations.AlterField(
            model_name='simulaciomillora',
            name='reduccioConsumPrevista',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='simulaciomillora',
            name='reduccioEmissionsPrevista',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='SimulacioMilloraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.FloatField(blank=True, help_text='Quantitat aplicada. Si és null, el motor en fa una estimació segons unitatBase.', null=True)),
                ('coberturaPercent', models.FloatField(default=100, help_text="Percentatge d'aplicació de la millora sobre l'edifici o sistema afectat.")),
                ('costEstimatParcial', models.FloatField(default=0)),
                ('reduccioConsumParcial', models.FloatField(default=0)),
                ('reduccioEmissionsParcial', models.FloatField(default=0)),
                ('impactePuntsParcial', models.FloatField(default=0)),
                ('resultatParcial', models.JSONField(blank=True, default=dict)),
                ('millora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_simulacio', to='buildings.catalegmillora')),
                ('simulacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='buildings.simulaciomillora')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
