# Generated by Django 5.2.12 on 2026-04-27 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0009_alter_catalegmillora_options_catalegmillora_activa_and_more'),
        ('buildings', '0009_alter_dadesenergetiques_qualificacioglobal'),
    ]

    operations = [
    ]
