# Generated by Django 5.2.12 on 2026-04-28 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0010_merge_20260427_2152'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='edifici',
            name='font_open_data',
            field=models.BooleanField(default=False, help_text="True si les dades bàsiques provenen d'open data CEE"),
        ),
        migrations.AddField(
            model_name='edifici',
            name='num_cas_origen',
            field=models.CharField(blank=True, help_text="Identificador CEE d'origen", max_length=100),
        ),
        migrations.AddField(
            model_name='edifici',
            name='tipologia_open_data',
            field=models.CharField(blank=True, choices=[('BlocPisos', 'Bloc de pisos'), ('Unifamiliar', 'Casa unifamiliar'), ('HabitatgeBloc', 'Habitatge individual en bloc'), ('Terciari', 'Terciari'), ('Desconegut', 'Desconegut')], default='Desconegut', max_length=20),
        ),
        migrations.CreateModel(
            name='ImportacioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(help_text='URL o nom del fitxer CSV', max_length=255)),
                ('data_inici', models.DateTimeField(auto_now_add=True)),
                ('data_fi', models.DateTimeField(blank=True, null=True)),
                ('total_files', models.IntegerField(default=0)),
                ('files_ok', models.IntegerField(default=0)),
                ('files_error', models.IntegerField(default=0)),
                ('edificis_creats', models.IntegerField(default=0)),
                ('habitatges_creats', models.IntegerField(default=0)),
                ('completada', models.BooleanField(default=False)),
                ('usuari', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importacions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importació open data',
                'ordering': ['-data_inici'],
            },
        ),
        migrations.CreateModel(
            name='ImportacioIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cas', models.CharField(blank=True, max_length=100)),
                ('motiu', models.TextField()),
                ('dades_raw', models.JSONField(blank=True, null=True)),
                ('importacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencies', to='buildings.importaciolog')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
