# Generated by Django 5.2.12 on 2026-04-28 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0011_edifici_font_open_data_edifici_num_cas_origen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadesEnergetiquesOpenData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualificacioGlobal', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=1, null=True)),
                ('consumEnergiaPrimaria', models.FloatField(default=0)),
                ('consumEnergiaFinal', models.FloatField(default=0)),
                ('emissionsCO2', models.FloatField(default=0)),
                ('costAnualEnergia', models.FloatField(default=0)),
                ('energiaCalefaccio', models.FloatField(default=0)),
                ('energiaRefrigeracio', models.FloatField(default=0)),
                ('energiaACS', models.FloatField(default=0)),
                ('energiaEnllumenament', models.FloatField(default=0)),
                ('emissionsCalefaccio', models.FloatField(default=0)),
                ('emissionsRefrigeracio', models.FloatField(default=0)),
                ('emissionsACS', models.FloatField(default=0)),
                ('emissionsEnllumenament', models.FloatField(default=0)),
                ('aillamentTermic', models.FloatField(default=0)),
                ('valorFinestres', models.FloatField(default=0)),
                ('normativa', models.CharField(blank=True, max_length=255)),
                ('einaCertificacio', models.CharField(blank=True, max_length=255)),
                ('motiuCertificacio', models.CharField(blank=True, max_length=255)),
                ('rehabilitacioEnergetica', models.BooleanField(default=False)),
                ('dataEntrada', models.DateField(blank=True, null=True)),
                ('teSolarTermica', models.BooleanField(default=False)),
                ('teSolarFotovoltaica', models.BooleanField(default=False)),
                ('teBiomassa', models.BooleanField(default=False)),
                ('teGeotermia', models.BooleanField(default=False)),
                ('edifici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dades_energetiques_opendata', to='buildings.edifici')),
            ],
            options={
                'verbose_name': 'Dades energètiques open data',
            },
        ),
    ]
