# Generated by Django 5.2.12 on 2026-05-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0013_milloraimplementada_administradorfinca_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='edifici',
            name='puntuacioBaseOpenData',
            field=models.FloatField(blank=True, editable=False, help_text='Building Health Score calculat a partir de les dades open data (CEE). Null si no hi ha dades open data associades.', null=True),
        ),
    ]
