# Generated by Django 5.2.12 on 2026-05-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0014_edifici_puntuaciobaseopendata'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadesenergetiquesopendata',
            name='metodeAgregacio',
            field=models.CharField(blank=True, default='', help_text="Mètode d'agregació de les dades (p.ex. 'primera_fila', 'mitjana').", max_length=50),
        ),
    ]
