# Generated by Django 5.2.12 on 2026-05-10 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0015_dadesenergetiquesopendata_metodeagregacio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habitatge',
            name='estatValidacio',
            field=models.CharField(choices=[('PendentDocumentacio', 'Pendent de documentació'), ('EnRevisió', 'En revisió'), ('Validada', 'Validada'), ('Rebutjada', 'Rebutjada')], default='EnRevisió', max_length=25),
        ),
        migrations.AddField(
            model_name='habitatge',
            name='solicitant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicituds_habitatge', to=settings.AUTH_USER_MODEL),
        ),
    ]
