# Generated by Django 5.2.12 on 2026-05-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0016_habitatge_estatvalidacio_habitatge_solicitant'),
    ]

    operations = [
        migrations.AddField(
            model_name='edifici',
            name='heatRiskFont',
            field=models.CharField(blank=True, editable=False, help_text="Font de les dades usades per calcular l'HRI: 'usuaris' o 'opendata'.", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='edifici',
            name='heatRiskIndex',
            field=models.FloatField(blank=True, editable=False, help_text='Heat Risk Index (0–100, 100=màxim risc). Null si manquen dades crítiques.', null=True),
        ),
    ]
