# Generated by Django 5.2.12 on 2026-05-18 20:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0017_edifici_heatriskfont_edifici_heatriskindex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='milloraimplementada',
            name='simulacio',
            field=models.ForeignKey(blank=True, help_text='Simulació aprovada que origina aquesta implementació, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implementacions_generades', to='buildings.simulaciomillora'),
        ),
        migrations.AddField(
            model_name='simulaciomillora',
            name='estatAplicacio',
            field=models.CharField(choices=[('esborrany', 'Esborrany'), ('en_votacio', 'En votació'), ('aprovada', 'Aprovada'), ('rebutjada', 'Rebutjada'), ('implementada', 'Implementada')], db_index=True, default='esborrany', max_length=20),
        ),
        migrations.AddField(
            model_name='simulaciomillora',
            name='votacioAprovadaAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VotacioSimulacioMillora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=255)),
                ('descripcio', models.TextField(blank=True)),
                ('dataInici', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataFi', models.DateTimeField()),
                ('quorumPercent', models.FloatField(default=75.0)),
                ('majoriaPercent', models.FloatField(default=50.0)),
                ('estat', models.CharField(choices=[('activa', 'Activa'), ('aprovada', 'Aprovada'), ('rebutjada', 'Rebutjada'), ('caducada', 'Caducada')], db_index=True, default='activa', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('creadaPer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votacions_simulacions_creades', to=settings.AUTH_USER_MODEL)),
                ('edifici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votacions_simulacions', to='buildings.edifici')),
                ('simulacio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='votacio', to='buildings.simulaciomillora')),
            ],
            options={
                'verbose_name': 'Votació de simulació de millora',
                'verbose_name_plural': 'Votacions de simulacions de millora',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='VotSimulacioMillora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentit', models.CharField(choices=[('favor', 'A favor'), ('contra', 'En contra')], max_length=10)),
                ('data', models.DateTimeField(auto_now=True)),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vots_simulacions', to=settings.AUTH_USER_MODEL)),
                ('votacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vots', to='buildings.votaciosimulaciomillora')),
            ],
            options={
                'verbose_name': 'Vot de simulació',
                'verbose_name_plural': 'Vots de simulacions',
                'ordering': ['-data'],
                'unique_together': {('votacio', 'usuari')},
            },
        ),
    ]
