# Generated by Django 5.2.12 on 2026-05-19 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0018_milloraimplementada_simulacio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadesenergetiques',
            name='aillamentTermic',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.05), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='dadesenergetiques',
            name='consumEnergiaFinal',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(450.0)]),
        ),
        migrations.AlterField(
            model_name='dadesenergetiques',
            name='consumEnergiaPrimaria',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(600.0)]),
        ),
        migrations.AlterField(
            model_name='dadesenergetiques',
            name='costAnualEnergia',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(15000.0)]),
        ),
        migrations.AlterField(
            model_name='dadesenergetiques',
            name='emissionsACS',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(40.0)]),
        ),
        migrations.AlterField(
            model_name='dadesenergetiques',
            name='emissionsCO2',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(150.0)]),
        ),
        migrations.AlterField(
            model_name='dadesenergetiques',
            name='emissionsCalefaccio',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='dadesenergetiques',
            name='emissionsEnllumenament',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(25.0)]),
        ),
        migrations.AlterField(
            model_name='dadesenergetiques',
            name='emissionsRefrigeracio',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(50.0)]),
        ),
        migrations.AlterField(
            model_name='dadesenergetiques',
            name='energiaACS',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(80.0)]),
        ),
        migrations.AlterField(
            model_name='dadesenergetiques',
            name='energiaCalefaccio',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(250.0)]),
        ),
        migrations.AlterField(
            model_name='dadesenergetiques',
            name='energiaEnllumenament',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(50.0)]),
        ),
        migrations.AlterField(
            model_name='dadesenergetiques',
            name='energiaRefrigeracio',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(120.0)]),
        ),
        migrations.AlterField(
            model_name='dadesenergetiques',
            name='valorFinestres',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(8.0)]),
        ),
    ]
