# Generated by Django 5.2.12 on 2026-05-19 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_propietari_llogater(apps, schema_editor):
    Habitatge = apps.get_model("buildings", "Habitatge")

    for habitatge in Habitatge.objects.select_related("usuari__profile").all():
        if not habitatge.usuari_id:
            continue

        role = getattr(getattr(habitatge.usuari, "profile", None), "role", None)

        if role == "owner" and not habitatge.propietari_id:
            habitatge.propietari_id = habitatge.usuari_id
            habitatge.save(update_fields=["propietari"])

        elif role == "tenant" and not habitatge.llogater_id:
            habitatge.llogater_id = habitatge.usuari_id
            habitatge.save(update_fields=["llogater"])


def reverse_backfill_propietari_llogater(apps, schema_editor):
    # No eliminem dades en rollback: són camps nous i Django ja els eliminarà si es desfà la migració.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0019_alter_dadesenergetiques_aillamenttermic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habitatge',
            name='llogater',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='habitatges_com_llogater',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='habitatge',
            name='propietari',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='habitatges_com_propietari',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='habitatge',
            name='rolSolicitat',
            field=models.CharField(
                blank=True,
                choices=[('owner', 'Propietari'), ('tenant', 'Llogater')],
                max_length=10,
                null=True,
            ),
        ),
        migrations.RunPython(
            backfill_propietari_llogater,
            reverse_backfill_propietari_llogater,
        ),
    ]
