# Generated by Django 5.2.12 on 2026-05-19 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0020_habitatge_owner_tenant_fields'),
        ('seasons', '0002_temporada_estat'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('descripcio', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('score', 'Puntuació'), ('emissions', 'Emissions'), ('data_quality', 'Qualitat de dades'), ('improvement', 'Millores'), ('progress', 'Progrés'), ('general', 'General')], default='general', max_length=30)),
                ('scope', models.CharField(choices=[('seasonal', 'Per temporada'), ('permanent', 'Permanent')], default='seasonal', max_length=20)),
                ('criteris', models.JSONField(blank=True, default=dict)),
                ('activa', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Definició d’insígnia',
                'verbose_name_plural': 'Definicions d’insígnies',
                'ordering': ['categoria', 'code'],
            },
        ),
        migrations.CreateModel(
            name='BuildingBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('valor_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignacions', to='buildings.badgedefinition')),
                ('edifici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='buildings.edifici')),
                ('temporada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building_badges', to='seasons.temporada')),
            ],
            options={
                'verbose_name': 'Insígnia d’edifici',
                'verbose_name_plural': 'Insígnies d’edificis',
                'ordering': ['-awarded_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('temporada__isnull', False)), fields=('edifici', 'temporada', 'badge'), name='unique_badge_per_edifici_temporada'), models.UniqueConstraint(condition=models.Q(('temporada__isnull', True)), fields=('edifici', 'badge'), name='unique_permanent_badge_per_edifici')],
            },
        ),
    ]
