# Generated by Django 5.2.12 on 2026-05-12 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0016_habitatge_estatvalidacio_habitatge_solicitant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFincaDocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendent'), ('running', 'Processant'), ('approved', 'Aprovada'), ('rejected', 'Rebutjada'), ('review', 'Revisió manual')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('edifici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='buildings.edifici')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminFincaVerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitxer', models.FileField(upload_to='verifications/%Y/%m/')),
                ('doc_type', models.CharField(choices=[('acta_junta', 'Acta de junta'), ('certificat', 'Certificat de nomenament'), ('contracte', "Contracte d'administració"), ('cert_col', 'Certificat col·legial'), ('identificatiu', 'Document identificatiu'), ('factura', 'Factura/document comunitat'), ('desconegut', 'Desconegut')], default='desconegut', max_length=30)),
                ('ocr_text', models.TextField(blank=True)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='verification.adminfincadocumentverification')),
            ],
        ),
        migrations.CreateModel(
            name='AdminFincaVerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('nom_detectat', models.CharField(blank=True, max_length=255)),
                ('dni_detectat', models.CharField(blank=True, max_length=20)),
                ('carrec_detectat', models.CharField(blank=True, max_length=100)),
                ('comunitat_detectada', models.CharField(blank=True, max_length=255)),
                ('vigencia_detectada', models.BooleanField(default=False)),
                ('explicacio', models.TextField(blank=True)),
                ('raw_llm_output', models.JSONField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_fetes', to=settings.AUTH_USER_MODEL)),
                ('verification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='verification.adminfincadocumentverification')),
            ],
        ),
    ]
