# Generated by Django 5.2.12 on 2026-05-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminfincadocumentverification',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminfincadocumentverification',
            name='score_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='adminfincadocumentverification',
            name='suggeriment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='adminfincaverificationdocument',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminfincaverificationdocument',
            name='score_flags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
