# Generated by Django 5.2.12 on 2026-03-11 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadesEnergetiques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualificacioGlobal', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=1)),
                ('consumEnergiaPrimaria', models.FloatField()),
                ('consumEnergiaFinal', models.FloatField()),
                ('emissionsCO2', models.FloatField()),
                ('costAnualEnergia', models.FloatField()),
                ('energiaCalefaccio', models.FloatField()),
                ('energiaRefrigeracio', models.FloatField()),
                ('energiaACS', models.FloatField()),
                ('energiaEnllumenament', models.FloatField()),
                ('emissionsCalefaccio', models.FloatField()),
                ('emissionsRefrigeracio', models.FloatField()),
                ('emissionsACS', models.FloatField()),
                ('emissionsEnllumenament', models.FloatField()),
                ('aillamentTermic', models.FloatField()),
                ('valorFinestres', models.FloatField()),
                ('normativa', models.CharField(max_length=255)),
                ('einaCertificacio', models.CharField(max_length=255)),
                ('motiuCertificacio', models.CharField(max_length=255)),
                ('rehabilitacioEnergetica', models.BooleanField(default=False)),
                ('dataEntrada', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GrupComparable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idGrup', models.IntegerField()),
                ('zonaClimatica', models.CharField(max_length=10)),
                ('tipologia', models.CharField(choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial'), ('Mixt', 'Mixt')], max_length=20)),
                ('rangSuperficie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Localitzacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrer', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('codiPostal', models.CharField(max_length=10)),
                ('barri', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('zonaClimatica', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Edifici',
            fields=[
                ('idEdifici', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('anyConstruccio', models.IntegerField()),
                ('tipologia', models.CharField(choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial'), ('Mixt', 'Mixt')], max_length=20)),
                ('superficieTotal', models.FloatField()),
                ('reglament', models.CharField(max_length=100)),
                ('orientacioPrincipal', models.CharField(max_length=50)),
                ('puntuacioBase', models.FloatField()),
                ('administradorFinca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edificis_administrats', to=settings.AUTH_USER_MODEL)),
                ('grupComparable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edificis', to='accounts.grupcomparable')),
                ('localitzacio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edifici', to='accounts.localitzacio')),
            ],
        ),
        migrations.CreateModel(
            name='Habitatge',
            fields=[
                ('referenciaCadastral', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('planta', models.CharField(max_length=10)),
                ('porta', models.CharField(max_length=10)),
                ('superficie', models.FloatField()),
                ('anyReforma', models.IntegerField(blank=True, null=True)),
                ('dadesEnergetiques', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dades_energetiques', to='accounts.dadesenergetiques')),
                ('edifici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitatges', to='accounts.edifici')),
                ('usuari', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habitatges_on_resideix', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
