# Generated by Django 5.2.12 on 2026-03-24 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('expired', 'Expirado'), ('revoked', 'Revocado')], max_length=20)),
                ('login_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('jti', models.CharField(db_index=True, max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Token Login Logs',
                'ordering': ['-login_at'],
                'indexes': [models.Index(fields=['user', '-login_at'], name='accounts_to_user_id_74ae6b_idx'), models.Index(fields=['status', '-login_at'], name='accounts_to_status_f96d30_idx')],
            },
        ),
    ]
