# Generated by Django 5.2.12 on 2026-03-11 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dadesenergetiques_grupcomparable_localitzacio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessDenialLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=20)),
                ('edifici_sol_licitat', models.CharField(blank=True, max_length=50)),
                ('accio', models.CharField(max_length=100)),
                ('motiu', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_denials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
