# Generated by Django 5.2.12 on 2026-05-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_token_login_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='documentPadro',
            field=models.FileField(blank=True, help_text="Document acreditatiu de l'administrador de finca.", null=True, upload_to='documents_admin/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='estatValidacioAdmin',
            field=models.CharField(choices=[('pendent', 'Pendent de validació'), ('aprovat', 'Aprovat'), ('rebutjat', 'Rebutjat')], default='pendent', max_length=20),
        ),
    ]
