# Generated by Django 5.2.12 on 2026-05-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_documentpadro_profile_estatvalidacioadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='estatValidacioAdmin',
            field=models.CharField(choices=[('pendent', 'Pendent de validació'), ('aprovat', 'Aprovat'), ('rebutjat', 'Rebutjat')], default='pendent', max_length=50),
        ),
    ]
