# Generated by Django 5.2.12 on 2026-05-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('password', 'Password'), ('google', 'Google')], default='password', max_length=20),
        ),
    ]
