# Generated by Django 5.2.12 on 2026-05-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text="Imatge/avatar del perfil de l'usuari.", null=True, upload_to='avatars/'),
        ),
    ]
