# Generated by Django 5.2.12 on 2026-05-19 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_moderation_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='moderationlog',
            new_name='chat_modera_moderat_10f684_idx',
            old_name='chat_modera_moderat_idx',
        ),
        migrations.RenameIndex(
            model_name='moderationlog',
            new_name='chat_modera_target__417986_idx',
            old_name='chat_modera_target__idx',
        ),
        migrations.RenameIndex(
            model_name='moderationlog',
            new_name='chat_modera_channel_b8867e_idx',
            old_name='chat_modera_channel_idx',
        ),
        migrations.RenameIndex(
            model_name='moderationlog',
            new_name='chat_modera_action_fc6688_idx',
            old_name='chat_modera_action__idx',
        ),
    ]
