@startuml

class Edifici {
    idEdifici : String
    anyConstruccio : int
    tipologia : TipusEdifici
    superficieTotal : float
    reglament : String
    orientacioPrincipal : Orientacio
}

class Habitatge {
  referenciaCadastral : String
  idHabitatge : String
  pis : String
  porta : String
  superficie : float
  anyReforma : int
}

class Localitzacio {
  adreca : String
  numero : int
  codiPostal : String
  barri : String
  latitud : float
  longitud : float
  zonaClimatica : String
}
class CertificatEnergetic {
    qualificacioGlobal : LletraEnergetica
    consumEnergiaPrimaria : float
    consumEnergiaFinal : float
    emissionsCO2 : float
    costAnualEnergia : float

    energiaCalefaccio : float
    energiaRefrigeracio : float
    energiaACS : float
    energiaEnllumenament : float

    emissionsCalefaccio : float
    emissionsRefrigeracio : float
    emissionsACS : float
    emissionsEnllumenament : float

    aillamentTermic : float
    valorFinestres : float

    normativa : String
    einaCertificacio : String
    motiuCertificacio : String
    rehabilitacioEnergetica : boolean
    dataEntrada : Date
}

class IndicadorEnergetic {
  consumEstimat : float
  indexResiliencia : float
  heatRiskScore : float
  rankingDistricte : int
}

class Usuari {
  idUsuari : String
  nom : String
  email : String
  rol : String
  dataRegistre : Date
}

class Resident{
  tipus : TipusResident
}
class AdministradorFinca{}

class InstalacioEnergetica {
  solarFotovoltaica : boolean
  solarTermica : boolean
  biomassa : boolean
  geotermica : boolean
  xarxaDistricte : boolean
  vehicleElectric : boolean
}

class Temporada {
  idTemporada : String
  nom : String
  dataInici : Date
  dataFi : Date
  activa : boolean
}

class Lliga {
  nom : String
  categoria : CategoriaRanking
  divisio : DivisioLliga
}

class Participacio {
  puntuacio : float
  posicio : int
  divisio : String
}

class GrupComparable {
  zonaClimatica : String
  tipologia : TipusEdifici
  rangSuperficie : String
}
class Missio {
  titol : String
  descripcio : String
  punts : int
  categoria : CategoriaRanking
}
class MissioEdifici {
  completada : boolean
  dataCompletada : Date
}

class SimulacioMillora {
  descripcio : String
  reduccioConsumPrevista : float
  reduccioEmissionsPrevista : float
  costEstimado : float
  estalviAnual: float
  dataSimulacio : Date
}

class Millora {
  nom : String
  descripcio : String
  categoria : String
  impactePunts : float
  parametres : String
}
class Vot {
  valor : float
  data : Date
}

class Informe {
  dataGeneracio : Date
  resum : String
}

class Xat {
  nom : String
}

class Missatge {
  text: String
  DataEnviament: Date
}


enum CategoriaRanking {
  EFICIENCIA
  RESILIENCIA
  PROGRES
}

enum DivisioLliga {
  Bronze
  Silver
  Gold
}

enum LletraEnergetica {
  A
  B
  C
  D
  E
  F
  G
}

enum TipusEdifici {
  Residencial
  Comercial
  Mixt
}

enum TipusResident {
  Propietari
  Llogater
}

enum Orientacio {
  Nord
  Sud
  Est
  Oest
}

' Relacions
Edifici "1" -up- "1" Localitzacio : ubicat_en >
Edifici "1" *-- "1..*" Habitatge : format_per >
Habitatge "1" -- "1" CertificatEnergetic : disposa_de >
Edifici "1" -up- "1" IndicadorEnergetic : genera
Edifici "1" -- "*" Informe

' Per un habitatge només hi haurà un compte d'usuari
Usuari "1" -- "*" Habitatge : resideix
Edifici "1..*" -- "0..1" AdministradorFinca : gestiona <
Edifici "1" -up- "0..1" InstalacioEnergetica : incorpora
AdministradorFinca --|> Usuari
Resident --|> Usuari
AdministradorFinca "1" -- "0..*" Informe : crea >

Temporada "1" *-- "*" Lliga
Lliga "1" -- "*" Participacio : inclou
Edifici "1" -left- "*" Participacio

Edifici "1..*" -right- "1" GrupComparable : pertany >

Temporada "*" -- "1..*" Missio : activa >
Participacio "1" -- "*" MissioEdifici
Missio "1" -- "*" MissioEdifici
' Equivalent a classe associativa, missió - edf
Edifici "1" -- "*" MissioEdifici

Edifici "1" -- "0..*" SimulacioMillora : proposa >
SimulacioMillora "1" -- "1" Millora

Usuari "1" -left- "0..*" Vot
SimulacioMillora "0..1" -right- "*" Vot

Xat "1" -- "1" Edifici : Té >
Xat "1..*" -- "1..*" Usuari
Xat "1" -- "0..*" Missatge : Pertany <
Usuari "1" -- "0..*" Missatge : envia >

note right of Usuari
{overlapping, incomplete}
end note

@enduml