# Generated by Django 5.2.12 on 2026-04-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id_temporada', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('dataInici', models.DateField()),
                ('dataFi', models.DateField()),
                ('activa', models.BooleanField(default=False)),
            ],
        ),
    ]
